#!/usr/bin/env bash
set -e
source "$(dirname "$0")/lib.sh"

build() {
  export NIXPKGS_ALLOW_UNFREE=1
  info "Starting build..."
  nix --extra-experimental-features 'nix-command flakes' build ".#${NIXAPPS_FLAKE_ATTR}" "$@"

  info "Cleaning up..."
  unlink ./result
}

main() {
  build "$@"
  success "Build complete!"
}

main "$@"
